language: rust
rust:
  - stable
cache: cargo

before_install:
  - sudo apt install -y libsdl2-2.0-0 libsdl2-gfx-1.0-0 libsdl2-mixer-2.0-0 libsdl2-ttf-2.0-0 libsdl2-image-2.0-0
  
addons:
  apt:
    update: true
